### PR TITLE
feat: add `@InjectQueueEvents` decorator

### PR DESCRIPTION
**Pull request by bilalshaikh42**

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@ejhayes great to see this is still active! We made a whole bunch of changes to this as a part of integrating it into our deployment. So most of these commits are not applicable to this repo (changing package name etc). But the last commit is the one that adds the actual feature. There are a few commits that make updates to the package requirements to make this work with newer versions of NestJs. 

I don't have much time for the next few days, bit after I'd be more than happy to make a clean pr that only includes the relevant changes

**Comment by ejhayes** [comment]
That'd be great @bilalshaikh42 -- happy to accept and merge that in when ready 😊

**Comment by bilalshaikh42** [comment]
Would you prefer to keep the CI/CD settings that you had the same? Or would it be okay to include the changes made to the release and testing/linting/etc workflows?

**Comment by ejhayes** [comment]
@bilalshaikh42 no need to add the npm run build as this is done as part of the release command. Bumping to node 16 sounds great. Thank you!

**Pull request closed without merging**
